import os
import re

with open('source.txt') as file:
    code = file.read()

words = re.findall(r'[A-Za-z_][A-Za-z0-9_]*', code)

code = re.sub(r' *& *', r' And ', code)
code = re.sub(r' *\| *', r' Or ', code)
code = re.sub(r' *:= *', r' = ', code)
code = re.sub(r'^', r'\t\tElseIf ', code, flags = re.MULTILINE)
code = re.sub(r'^\t\tElseIf ', r'\n\tPrivate Sub Execute()\n\t\tIf ', code)
code = re.sub(r' *\[ *', r' Then\n\t\t\t', code)
code = re.sub(r' *; *] *', r'', code)
code = re.sub(r' *; *', r'\n\t\t\t', code)
code = re.sub(r'\s*ElseIf $', r'', code)
code += '\n\t\tEnd If\n\tEnd Sub\nEnd Class'

skip = ['accelX', 'accelY', 'accelZ', 'output', 'backSpace', 'LED']
for item in words:
    if item not in skip:
        skip.append(item)
        code = '\tPrivate ' + item + ' As Single\n' + code

code = "'code below generated by translate.py\n" + code
        
with open(os.path.join('WiimotePLMAM1', 'Form1.vb')) as file:
    vbcode = file.read()

vbcode = vbcode[0:vbcode.index("'code below generated by translate.py")] + code

with open(os.path.join('WiimotePLMAM1', 'Form1.vb'), 'w') as file:
    file.write(vbcode)
